### ISSUE TITLE
How it differs from other realizations?

### ISSUE THREAD

**Issue by AlexByte** [khrabrovart/Citrina#1]
Other realizations aren't full-blown and high-performance?

**Comment by khrabrovart** [comment]
Thanks for question.
Current realization parses official VK JSON scheme to get request and response models, so this approach is much easier to maintain and keep up to date. No need to parse every method by hands.
It is also supports async operations and make it easy to get VK data as fast as possible. Request queue manages all the requests and does not throw the "Too many requests per second" error. I don't know any other VK API wrappers for .NET that offer similar functionality.

**Comment by AlexByte** [comment]
How do you convert a schema into classes?
I don't  like GPL, because it can not be used in applications with private code. Well at least not AGPL.

**Comment by khrabrovart** [comment]
For now I'm using the [Json.NET Schema](http://www.newtonsoft.com/jsonschema) and [T4 templates](https://msdn.microsoft.com/en-us/library/bb126445.aspx) to convert JSON to C# code. In the future I wanna use something more elegant and then push it to the GitHub too.

And I'll think about the license :-)

**Comment by AlexByte** [comment]
Why did not you publish the T4 templates?

**Comment by khrabrovart** [comment]
T4 templates are currently located in another repo (private repo). It's because the Citrina is my primary project and JSON schema converter is just a tool. I will publish this converter when I bring it to a better condition.

**Comment by AlexByte** [comment]
> Current realization parses official VK JSON scheme to get request and response models.

I think that this should be written in readme.

**Comment by khrabrovart** [comment]
That's right. I added this in readme.
