### ISSUE TITLE
Problem with to get an uploader from the Citrina client.

### ISSUE THREAD

**Issue by AlesiaMianitskaya** [khrabrovart/Citrina#4]
Hello,
I installed Citrina via Nuget package manager and wanted to set owner photo, but when I tried to get an uploader from the Citrina client saw this error - 'CitrinaClient' does not contain a definition for Uploader.
Could you help me with this problem or give any tips?

Regards.
![1](https://user-images.githubusercontent.com/22531340/33238583-c51f2584-d2a1-11e7-811e-0f9c6b94a25c.PNG)

**Comment by khrabrovart** [comment]
Hello.
Yes you are right. CitrinaClient actually doesn't contain a definition for Uploader.

Now the uploader is published as a separate package: [Citrina.Uploader](https://www.nuget.org/packages/Citrina.Uploader/). I've just finished with it and it's in beta now. 
You can also read the [File Uploading](https://github.com/khrabrovart/Citrina#file-uploading) section for more information on how to use it.

Thanks.
